INSERT INTO stories ( user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (1, 'The Adventure Begins', 'A story about a hero starting their journey.', 'In a quaint village nestled amidst rolling hills, young Lily longed for excitement beyond her mundane life. Every day, she gazed at the horizon, dreaming of far-off lands and thrilling escapades.One morning, an enigmatic letter arrived at her doorstep. It bore the emblem of a hidden treasure map and a cryptic message, "The Adventure Begins." Filled with curiosity and courage, Lily embarked on her quest.', false, '2023-07-31 12:34:56', null, false);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (1, 'Mystery in the Manor', 'A spooky mystery in an old mansion.', 'In the moonlit night, a haunting glow emanated from the old abandoned manor. Local legends spoke of a hidden mystery within its walls. Curiosity led a brave group to explore. Whispers echoed, doors creaked, and shadows danced. As they unraveled clues, a chilling secret emerged.', false, '2023-07-30 18:45:12', '2023-07-31 09:15:00', true);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (2, 'The Lost Artifact', 'An archaeologist''s quest for a legendary artifact.', 'In the heart of the dense jungle, an ancient legend whispered of a lost artifact of immense power. The tale reached the ears of intrepid archaeologist, Dr. Amelia Hartley. Determined to unearth the truth, she embarked on an arduous expedition. Amidst tangled vines and perilous pitfalls, Amelia''s team discovered the temple. At its core lay the artifact—a glowing crystal said to grant extraordinary abilities. Yet, with great power came great peril. As they returned, rival treasure hunters pursued them relentlessly. Fearing the artifact''s misuse, Amelia made a fateful choice. She hid the crystal deep within an undiscovered tomb, guarded by riddles only the worthy could solve. With the artifact concealed, Amelia understood that some secrets were better left untouched. And so, she returned home, cherishing the knowledge that the lost artifact remained safe, protecting the world from its own desires.', true, '2023-07-29 09:22:10', null, true);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (5, 'Sci-Fi Adventure', 'Exploring the universe in a spaceship.', 'In the distant future, aboard the interstellar starship "Cosmos," a diverse crew embarked on an epic sci-fi adventure. Their mission: to explore uncharted galaxies and seek extraterrestrial life.Captain Alex, a brilliant strategist, led the team with Commander Ava, an expert in alien linguistics. Together, they navigated through cosmic anomalies and encountered alien civilizations.', false, '2023-07-28 15:30:00', '2023-07-31 11:05:30', true);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (3, 'The Enchanted Forest', 'A magical journey through a mystical forest.', 'In the heart of the kingdom, shrouded in mystery, lay the Enchanted Forest—a place where dreams and reality merged. Whispering leaves and twinkling fireflies accompanied anyone daring enough to venture through its ethereal veil. Legend spoke of a guardian, a mystical being known as the Forest Sprite, who protected the forest''s enchantment. Many sought her wisdom, but few were granted an audience. One day, Emily, a curious young girl with a pure heart, wandered into the forest. Drawn by its allure, she encountered the Forest Sprite beneath a majestic oak tree. The sprite sensed Emily''s kind spirit and shared a wondrous secret: the forest possessed a magical portal that could transport her to her heart''s desire. Guided by the sprite, Emily embarked on an extraordinary journey. Along the way, she encountered talking animals, enchanted flora, and benevolent spirits, learning valuable lessons about empathy and humility.

', true, '2023-07-27 11:11:11', null, true);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (2, 'The Time Traveler', 'An adventurer travels through time.', 'In a quaint attic, young Emma discovered a dusty, brass pocket watch. Little did she know that it belonged to her eccentric great-grandfather, a renowned scientist and time traveler. One fateful day, as the clock struck midnight, the watch''s gears whirred to life, engulfing Emma in a dazzling vortex. She found herself in a bustling Victorian-era street, bewildered by the sight of horse-drawn carriages and gas lamps. Amid her time-traveling escapades, Emma met her great-grandfather in his youth. He explained the watch''s power and entrusted her with its guardianship, urging her to protect history''s integrity. Traveling through epochs, Emma witnessed historic events and encountered influential figures. From witnessing the moon landing to sharing tea with Leonardo da Vinci, each journey enriched her understanding of humanity''s tapestry. With newfound purpose, Emma returned to her time, cherishing the watch''s power, safeguarding its secrets, and vowing to become a responsible steward of time''s immeasurable gift. The attic became her portal, and as a time traveler, Emma would weave her own chapter into history''s epic tale.', true, '2023-07-26 09:00:00', '2023-07-31 16:30:20', false);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES (5, 'The Haunted Ship', 'A ghostly tale on a haunted ship.', 'Amidst a fog-laden harbor, sailors whispered tales of "The Phantom Tide," a haunted ship that emerged only on moonless nights. Captain Morgan, undeterred by superstitions, embarked on a daring quest to find the elusive vessel. As they ventured into the abyss, eerie shadows danced on the water''s surface. Strange noises echoed through the hull, and ghostly apparitions appeared on the deck. Crew members trembled, but Captain Morgan stood resolute. In the heart of the ship, they discovered a tattered journal, revealing a tragic tale of mutiny and lost souls condemned to roam the seas. The spirits sought peace and release from their eternal torment. Driven by compassion, Captain Morgan devised a plan to break the curse. With bravery and a heartfelt plea, he offered forgiveness to the tormented souls. As the moon emerged, the phantom ship faded, and the harbor was tranquil once more.', true, '2023-07-25 14:22:33', '2023-07-31 08:45:00', true);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES ( 4, 'Fantasy Kingdom', 'A tale about a kingdom in a fantasy world called Elordia.', 'In the realm of Eldoria, a magnificent Fantasy Kingdom thrived under the rule of Queen Isabella. The kingdom''s lush forests, enchanting rivers, and majestic mountains were home to mythical creatures and wise wizards. Princess Elara, the queen''s daughter, possessed a unique gift—the ability to communicate with animals. Her bond with the mystical creatures of Eldoria was unparalleled.', false, '2023-07-24 16:55:40', null, false);

INSERT INTO stories (user_id, title, description, content, completed, created_at, completed_at, is_fav)
VALUES ( 1, 'The Star Seeker', 'A young girl embarks on a daring quest to catch a falling star.', 'Once upon a moonlit night, little Luna gazed up at the vast expanse of stars, longing for something extraordinary. With her heart set on capturing a falling star, she fashioned a makeshift spaceship from cardboard boxes and set out on her celestial journey. Guided by her unwavering belief and the twinkling constellations, Luna soared through galaxies, encountering dazzling comets and nebulae. Her determination led her to the edge of the universe, where she spotted a radiant star gracefully plummeting towards a distant planet.', false, '2023-07-24 16:55:40', null, false);
